// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://smwhixcsmyyyoympqdcy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNtd2hpeGNzbXl5eW95bXBxZGN5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTgwMjgxMjcsImV4cCI6MjA3MzYwNDEyN30.AnuVoPcfwQfMChPSfyZffvd_BdS0fYF-inUNHb8VjOs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});